"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/client";
import { toast } from "sonner";

export default function LoyaltySettings() {
  const [config, setConfig] = useState(null); const [saving, setSaving] = useState(false);
  useEffect(() => { api("/loyalty/settings").then(setConfig).catch((e) => toast.error(e.message)); }, []);
  if (!config) return <section className="panel settings-card"><h2>Loyalty Program</h2><p className="muted">Loading loyalty settings…</p></section>;
  const set = (path, value) => { const [group, key] = path.split("."); setConfig((c) => key ? { ...c, [group]: { ...c[group], [key]: value } } : { ...c, [group]: value }); };
  const field = (path, label, min = 0, max = 100000) => <label>{label}<input type="number" min={min} max={max} step="0.01" value={path.includes(".") ? config[path.split(".")[0]][path.split(".")[1]] : config[path]} onChange={(e) => set(path, Number(e.target.value))}/></label>;
  return <section className="panel settings-card" id="settings-loyalty"><header><div><h2>Loyalty &amp; Rewards</h2><p>Reward regular customers. Changes apply to future sales only.</p></div></header><div className="payment-settings"><Toggle title="Enable Loyalty Program" text="Keep existing balances safely stored when disabled." checked={config.enabled} onChange={(v) => set("enabled", v)}/><Toggle title="Loyalty Wallet" text="Cashback wallet and checkout redemption." checked={config.wallet.enabled} onChange={(v) => set("wallet.enabled", v)}/><Toggle title="Digital Stamp Card" text="Unlock a free drink after eligible purchases." checked={config.stamp.enabled} onChange={(v) => set("stamp.enabled", v)}/><Toggle title="Visit Streak" text="Reward repeat visits." checked={config.visit.enabled} onChange={(v) => set("visit.enabled", v)}/><Toggle title="Birthday Reward" text="Offer an annual birthday reward." checked={config.birthday.enabled} onChange={(v) => set("birthday.enabled", v)}/></div><div className="settings-fields">{field("wallet.cashbackPercentage", "Cashback (%)", 0, 100)}{field("wallet.minimumBillAmount", "Minimum purchase (₹)")}{field("wallet.maximumCashbackPerSale", "Maximum cashback per sale (₹)")}{field("wallet.minimumRedemption", "Minimum wallet redemption (₹)")}{field("wallet.maximumRedemptionPercent", "Maximum wallet redemption (%)", 0, 100)}{field("stamp.requiredPurchases", "Stamps required", 1, 100)}{field("stamp.maximumFreeProductValue", "Maximum free drink value (₹)")}{field("visit.requiredVisits", "Visits required", 1, 100)}{field("visit.periodDays", "Visit period (days)", 1, 365)}{field("visit.rewardAmount", "Visit reward (₹)")}{field("birthday.rewardValue", "Birthday reward (₹)")}</div><button type="button" className="button primary" disabled={saving} onClick={async()=>{setSaving(true);try{await api("/loyalty/settings",{method:"PATCH",body:config});toast.success("Loyalty settings saved")}catch(e){toast.error(e.message)}finally{setSaving(false)}}}>{saving?"Saving…":"Save Loyalty Settings"}</button></section>;
}
function Toggle({ title, text, checked, onChange }) { return <label className="setting-toggle"><span><strong>{title}</strong><small>{text}</small></span><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/><i aria-hidden="true"/></label>; }
