"use client";
import { useState } from "react";
import BackupSettings from "./backup-settings";
import { Banknote, CalendarDays, ChevronDown, CreditCard, Download, Gift, Info, Printer, Smartphone, Ticket, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { formatCurrency as money } from "@/lib/client";
import { SettingsCard as Card, FormField as Field, ToggleRow, Switch, useSettingsDraft } from "./settings-ui";
const receiptToggles=[["showLogo","Show business logo"],["showCustomer","Show customer details"],["showCashier","Show cashier / user name"],["showPayment","Show payment method"],["showLoyalty","Show loyalty summary"]];
export function InvoiceSettings({preview,now,onPreview}) {
 const {draft}=useSettingsDraft(),sequence=Math.max(Number(draft.startingNumber)||1,(draft.lastIssuedSequence||0)+1);
 const parts=new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(now),date=["year","month","day"].map(key=>parts.find(p=>p.type===key)?.value).join("");
 return <><Card title="Invoice Numbering" description="Define the format used for future invoices."><div className="sm-grid"><Field path="invoicePrefix" label="Invoice Prefix" help="For example, INV-" max={12}/><Field path="invoiceNumberFormat" label="Invoice Format" options={[["DATE_SEQUENCE","Date + Sequence"],["SEQUENCE","Sequence only"],["DATETIME_SEQUENCE","Date & time + Sequence"]]}/><Field path="invoiceSequencePadding" label="Sequence Style" type="number" options={[1,2,3,4,5,6].map(n=>[n,String(1).padStart(n,"0")])}/><Field path="startingNumber" label="Next Invoice Sequence" type="number" min={(draft.lastIssuedSequence||0)+1} max={999999999} step={1} help={"Last issued sequence: "+(draft.lastIssuedSequence||0)+". Existing invoices keep their numbers."}/></div><div className="sm-invoice-preview"><small>LIVE INVOICE PREVIEW · INDIA STANDARD TIME</small><strong>{preview}</strong><div><span><b>{draft.invoicePrefix}</b>Prefix</span>{draft.invoiceNumberFormat!=="SEQUENCE"&&<span><b>{date}</b>Date</span>}<span><b>{String(sequence).padStart(Number(draft.invoiceSequencePadding)||1,"0")}</b>Sequence</span></div></div><p className="sm-info"><Info size={16}/>Changes only apply to future invoices.</p></Card><Card title="Receipt Settings" description="Choose the details your customers see on their receipt."><div className="sm-grid"><Field path="receiptSize" label="Receipt Size" options={["58mm","80mm"]}/><Field path="receiptFooter" label="Receipt Footer" max={300}/></div>{receiptToggles.map(([key,label])=><ToggleRow key={key} path={"receipt."+key} label={label}/>)}<button className="button secondary" onClick={onPreview}><Printer size={16}/>Preview Receipt</button></Card></>;
}
export function CheckoutSettings() {return <><Card title="Quick Sale" description="Set up a comfortable workflow for your counter."><div className="sm-grid"><Field path="checkout.defaultQuantity" label="Default sale quantity" type="number" min={1} max={999} step={1}/><Field path="checkout.customerPrompt" label="Ask for customer during checkout" options={[["NEVER","Never"],["OPTIONAL","Optional"],["REQUIRED","Required"]]}/></div><ToggleRow path="checkout.allowCustomQuantity" label="Allow custom quantity" description="When disabled, product selections add the default quantity; manual adjustments are disabled."/><ToggleRow path="checkout.allowItemNotes" label="Allow item notes"/></Card><Card title="Cash & Split Payments"><ToggleRow path="checkout.cashAmountEntry" label="Enable cash amount entry" description="Enter the amount received and calculate change to return."/><ToggleRow path="checkout.splitPayment" label="Split Payment" description="Combine Cash, UPI and Card. At least two enabled methods are needed."/><p className="sm-info">₹500 received − ₹320 sale = ₹180 change</p></Card><Card title="Sale Confirmation"><ToggleRow path="checkout.showSuccess" label="Show sale success modal"/><ToggleRow path="checkout.autoPrint" label="Auto print after sale" description="Opens the browser print dialog for the completed receipt."/><ToggleRow path="checkout.returnToNewSale" label="Return to New Sale after completion" description="Clear the product search and category for the next customer. When disabled, keep the current product view."/></Card></>;}
export function PaymentSettings() {
 const {draft,set}=useSettingsDraft();const [error,setError]=useState("");
 function change(method,enabled){const next=enabled?[...draft.paymentMethods,method]:draft.paymentMethods.filter(m=>m!==method);if(!next.length){setError("At least one payment method must remain enabled.");return;}setError("");set("paymentMethods",next);}
 return <Card title="Payment Methods" description="Choose how customers can pay at checkout.">{[["Cash",Banknote,"Accept cash payments"],["UPI",Smartphone,"Accept UPI payments"],["Card",CreditCard,"Accept debit and credit card payments"]].map(([method,Icon,description])=><div key={method} className="sm-payment" data-setting={method.toLowerCase()}><Icon size={22}/><div><strong>{method==="UPI"?"UPI / GPay":method}</strong><small>{description}</small></div><span className="sm-toggle-status">{draft.paymentMethods.includes(method)?"Enabled":"Disabled"}</span><Switch label={"Accept "+method} checked={draft.paymentMethods.includes(method)} onChange={value=>change(method,value)}/></div>)}{error&&<p className="sm-error" role="alert">{error}</p>}{draft.paymentMethods.includes("UPI")&&<div className="sm-grid"><Field path="upiId" label="UPI ID" help="Optional · displayed with UPI payment instructions at checkout." max={100}/></div>}</Card>;
}
export function DiscountSettings() {const {draft,set,errors}=useSettingsDraft();return <Card title="Discounts" description="Set consistent discount rules for every checkout."><ToggleRow path="discountEnabled" label="Enable Discounts" description="Allow discounts during checkout."/>{draft.discountEnabled&&<><div className="sm-discount-types" data-setting="discounts.types"><strong>Allowed Discount Types</strong>{[["percentage","Percentage"],["fixed","Fixed Amount"]].map(([key,label])=><label key={key}><input type="checkbox" checked={draft.discounts.types.includes(key)} onChange={e=>set("discounts.types",e.target.checked?[...draft.discounts.types,key]:draft.discounts.types.filter(v=>v!==key))}/>{label}</label>)}{errors["discounts.types"]&&<small className="sm-error">{errors["discounts.types"]}</small>}</div><div className="sm-grid"><Field path="discounts.maximumPercentage" label="Maximum percentage discount" type="number" min={0} max={100} step="0.01"/><Field path="discounts.maximumFixed" label="Maximum fixed discount (₹)" type="number" min={0} max={1000000} step="0.01"/></div><ToggleRow path="discounts.requireReason" label="Require discount reason"/><p className="sm-info">Example: a ₹500 sale with {Math.min(10,Number(draft.discounts.maximumPercentage)||0)}% discount = {money(500*(1-Math.min(10,Number(draft.discounts.maximumPercentage)||0)/100))}</p></>}</Card>;}
export const programList=[["wallet","Wallet Cashback",WalletCards,"Give customers a percentage of qualifying purchases."],["stamp","Digital Stamp Card",Ticket,"Reward repeat purchases with a free item."],["visit","Visit Streak",CalendarDays,"Reward customers who make repeat visits within a period."],["birthday","Birthday Reward",Gift,"Offer a special reward during the customer’s birthday period."]];
export function LoyaltySettings({expanded,setExpanded}) {
 const {draft}=useSettingsDraft(),l=draft.loyalty;
 const summaries={wallet:l.wallet.cashbackPercentage+"% cashback · Min. "+money(l.wallet.minimumBillAmount),stamp:l.stamp.requiredPurchases+" purchases · Reward up to "+money(l.stamp.maximumFreeProductValue),visit:l.visit.requiredVisits+" visits in "+l.visit.periodDays+" days · "+money(l.visit.rewardAmount),birthday:l.birthday.rewardType==="PERCENTAGE_DISCOUNT"?l.birthday.rewardValue+"% discount":money(l.birthday.rewardValue)+(l.birthday.rewardType==="WALLET"?" wallet credit":" discount")};
 return <><Card title="Loyalty & Rewards" description="Reward returning customers and encourage repeat visits."><ToggleRow path="loyalty.enabled" label="Loyalty Program" description={l.enabled?"Active · reward customers on qualifying purchases.":"Disabled · balances, history and configurations remain stored."}/></Card><div className={"sm-program-grid "+(!l.enabled?"sm-programs-paused":"")}>{programList.map(([key,name,Icon,description])=><article className="sm-program" key={key} data-setting={"loyalty."+key}><header><span className="sm-program-icon"><Icon size={21}/></span><div><h3>{name}</h3><p>{description}</p></div></header><ToggleRow path={"loyalty."+key+".enabled"} label={"Enable "+name} disabled={!l.enabled}/><div className="sm-program-summary"><span>{summaries[key]}</span><button disabled={!l.enabled} aria-expanded={expanded===key} className="sm-text-button" onClick={()=>setExpanded(expanded===key?null:key)}>Configure <ChevronDown size={15}/></button></div>{expanded===key&&<fieldset disabled={!l.enabled} className="sm-program-fields"><ProgramFields program={key}/></fieldset>}</article>)}</div></>;
}
function ProgramFields({program:k}) {const {draft}=useSettingsDraft(),l=draft.loyalty;const n=(key,label,min=0,max=1000000,step="0.01")=><Field path={"loyalty."+k+"."+key} label={label} type="number" min={min} max={max} step={step}/>;
 return <>{k==="wallet"&&<>{n("cashbackPercentage","Cashback rate (%)",0,100)}{n("minimumBillAmount","Minimum purchase (₹)")}{n("maximumCashbackPerSale","Maximum cashback per sale (₹)")}<small>At the current rate, a ₹500 purchase earns {money(500>=l.wallet.minimumBillAmount?Math.min(500*l.wallet.cashbackPercentage/100,l.wallet.maximumCashbackPerSale):0)}.</small></>}{k==="stamp"&&<>{n("requiredPurchases","Purchases required",1,100,1)}{n("maximumFreeProductValue","Maximum free item value (₹)")}<small>After {l.stamp.requiredPurchases} qualifying purchases, the customer earns one reward.</small></>}{k==="visit"&&<>{n("requiredVisits","Visits required",1,100,1)}{n("periodDays","Within days",1,365,1)}{n("rewardAmount","Reward value (₹)")}<small>Visits must qualify within the configured period.</small></>}{k==="birthday"&&<><Field path="loyalty.birthday.rewardType" label="Reward type" options={[["WALLET","Wallet Credit"],["PERCENTAGE_DISCOUNT","Percentage Discount"],["FIXED_DISCOUNT","Fixed Discount"]]}/>{n("rewardValue",l.birthday.rewardType==="PERCENTAGE_DISCOUNT"?"Reward value (%)":"Reward value (₹)",0,l.birthday.rewardType==="PERCENTAGE_DISCOUNT"?100:1000000)}<Field path="loyalty.birthday.availability" label="Valid for" options={[["DAY","Birthday only"],["WEEK","Birthday week"],["MONTH","Birthday month"]]}/><small>Birthday week includes the birthday and following six days. Redeem once per calendar year.</small></>}</>;
}
export function PrintingSettings({onPreview}) {return <Card title="Receipt Printer" description="Use the browser print dialog with your connected receipt printer."><div className="sm-grid"><Field path="receiptSize" label="Preferred paper width" options={["58mm","80mm"]}/><Field path="receipt.copies" label="Number of copies" type="number" min={1} max={5} step={1}/></div><ToggleRow path="checkout.autoPrint" label="Auto-print receipt after completed sale"/>{receiptToggles.map(([key,label])=><ToggleRow key={key} path={"receipt."+key} label={label.replace("Show","Print")}/>)}<button className="button secondary" onClick={onPreview}><Printer size={16}/>Test Print</button><p className="sm-info">Choose your receipt printer in the browser dialog. These preferences are shared with Invoice & Receipt.</p></Card>;}
export function DataSettings({onReset}) {
 const [exporting,setExporting]=useState(null);
 async function download(kind){setExporting(kind);try{const response=await fetch("/api/settings?export="+kind);if(!response.ok)throw new Error((await response.json()).message||"Unable to export data");const url=URL.createObjectURL(await response.blob()),a=document.createElement("a");a.href=url;a.download="karikku-"+kind+".csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){toast.error(e.message);}finally{setExporting(null);}}
 return <><Card title="Export Data" description="Download your saved records as CSV files."><div className="sm-export-grid">{["sales","expenses","products","customers"].map(kind=><button key={kind} className="button secondary" disabled={Boolean(exporting)} onClick={()=>download(kind)}><Download size={16}/>{exporting===kind?"Exporting...":"Export "+kind[0].toUpperCase()+kind.slice(1)}</button>)}</div></Card><BackupSettings/><section className="sm-danger"><h2>Reset Settings</h2><p>Restore default preferences. Sales, invoice history and customer balances are retained. Review the defaults before saving.</p><button className="button danger" onClick={onReset}>Reset settings to defaults</button></section></>;
}

