"use client";
import { useEffect, useRef, useState } from "react";
import { Building2, CreditCard, Database, Gift, Printer, ReceiptText, Save, Search, ShoppingBasket, Tags, X } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/client";
import { formatInvoiceNumber } from "@/lib/invoice-number";
import { settingSchema } from "@/lib/validation";
import { settingsWithDefaults } from "@/lib/settings-config";
import Modal from "@/components/modal";
import { ReceiptModal } from "@/components/sales/receipt";
import { SettingsContext, setPath } from "./settings-ui";
import { BusinessSettings, InvoiceSettings, CheckoutSettings, PaymentSettings, DiscountSettings, LoyaltySettings, PrintingSettings, DataSettings } from "./settings-sections";
import "./settings.css";
const categories=[["general","General",Building2],["invoice","Invoice & Receipt",ReceiptText],["checkout","Checkout",ShoppingBasket],["payments","Payments",CreditCard],["discounts","Discounts",Tags],["loyalty","Loyalty & Rewards",Gift],["printing","Printing",Printer],["data","Data & Backup",Database]];
const index=[
 ["loyalty","loyalty.wallet.cashbackPercentage","Cashback rate"],["loyalty","loyalty.wallet.minimumBillAmount","Minimum purchase"],["loyalty","loyalty.wallet.maximumCashbackPerSale","Maximum cashback per sale"],["loyalty","loyalty.stamp.requiredPurchases","Purchases required"],["loyalty","loyalty.stamp.maximumFreeProductValue","Maximum free item value"],["loyalty","loyalty.visit.requiredVisits","Visits required"],["loyalty","loyalty.visit.periodDays","Within days"],["loyalty","loyalty.visit.rewardAmount","Visit reward value"],["loyalty","loyalty.birthday.rewardType","Birthday reward type"],["loyalty","loyalty.birthday.rewardValue","Birthday reward value"],["loyalty","loyalty.birthday.availability","Birthday reward validity"],
 ["general","businessName","Business Name"],["general","logo","Business Logo"],["general","phone","Phone Number"],["general","email","Email Address"],["general","address","Address"],["general","currency","Currency"],
 ["invoice","invoicePrefix","Invoice Prefix"],["invoice","invoiceNumberFormat","Invoice Format"],["invoice","invoiceSequencePadding","Sequence Style"],["invoice","startingNumber","Next Invoice Sequence"],["invoice","receiptSize","Receipt Size"],["invoice","receiptFooter","Receipt Footer"],
 ["checkout","checkout.defaultQuantity","Default sale quantity"],["checkout","checkout.allowCustomQuantity","Allow custom quantity"],["checkout","checkout.allowItemNotes","Item notes"],["checkout","checkout.customerPrompt","Customer at checkout"],["checkout","checkout.cashAmountEntry","Cash amount entry"],["checkout","checkout.splitPayment","Split Payment"],["checkout","checkout.showSuccess","Sale success modal"],["checkout","checkout.autoPrint","Auto print after sale"],["checkout","checkout.returnToNewSale","Return to New Sale"],
 ["payments","cash","Cash payments"],["payments","upi","UPI / GPay"],["payments","card","Card payments"],["payments","upiId","UPI ID"],
 ["discounts","discountEnabled","Enable Discounts"],["discounts","discounts.types","Allowed Discount Types"],["discounts","discounts.maximumPercentage","Maximum percentage discount"],["discounts","discounts.maximumFixed","Maximum fixed discount"],["discounts","discounts.requireReason","Discount reason"],
 ["loyalty","loyalty.enabled","Loyalty Program"],["loyalty","loyalty.wallet","Wallet Cashback"],["loyalty","loyalty.stamp","Digital Stamp Card"],["loyalty","loyalty.visit","Visit Streak"],["loyalty","loyalty.birthday","Birthday Reward"],
 ["printing","receiptSize","Printer paper width"],["printing","receipt.copies","Number of copies"],["printing","receipt.showLogo","Print business logo"],["printing","receipt.showCustomer","Print customer details"],["printing","receipt.showCashier","Print cashier name"],["printing","receipt.showPayment","Print payment method"],["printing","receipt.showLoyalty","Print loyalty summary"],["data","","Export sales expenses products customers CSV backup reset"]
];
const fields=Object.keys(settingSchema.shape);
const payload = draft => Object.fromEntries(fields.filter(key=>draft[key]!==undefined).map(key=>[key,draft[key]]));
const prepare = (initial,loyalty) => ({...settingsWithDefaults(initial),loyalty,startingNumber:Math.max(initial.startingNumber||1,(initial.lastIssuedSequence||0)+1)});
export default function SettingsPage({initial,initialLoyalty}) {
 const [savedSettings,setSavedSettings]=useState(()=>prepare(initial,initialLoyalty)),[draftSettings,setDraftSettings]=useState(()=>prepare(initial,initialLoyalty));
 const [tab,setTab]=useState("general"),[query,setQuery]=useState(""),[expanded,setExpanded]=useState(null),[highlight,setHighlight]=useState(""),[errors,setErrors]=useState({}),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState(""),[confirm,setConfirm]=useState(null),[receipt,setReceipt]=useState(null),[now,setNow]=useState(()=>new Date());
 const lock=useRef(false),skipGuard=useRef(false),root=useRef(null);
 const dirty=JSON.stringify(payload(draftSettings))!==JSON.stringify(payload(savedSettings));
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{
   if(!dirty)return;
   const unload=e=>{if(!skipGuard.current){e.preventDefault();e.returnValue="";}};
   const click=e=>{const link=e.target.closest?.("a[href]");if(!link||link.target==="_blank"||link.hasAttribute("download")||e.ctrlKey||e.metaKey||e.shiftKey||skipGuard.current)return;const url=new URL(link.href);if(url.origin===location.origin&&url.pathname===location.pathname)return;e.preventDefault();e.stopPropagation();setConfirm({type:"leave",href:link.href});};
   // Navigation API covers browser back/forward without changing the history stack.
   const navigate=e=>{if(e.navigationType==="traverse"&&e.cancelable&&!skipGuard.current&&!window.confirm("Discard changes? Your unsaved settings will be lost."))e.preventDefault();};
   window.addEventListener("beforeunload",unload);document.addEventListener("click",click,true);window.navigation?.addEventListener("navigate",navigate);
   return()=>{window.removeEventListener("beforeunload",unload);document.removeEventListener("click",click,true);window.navigation?.removeEventListener("navigate",navigate);};
 },[dirty]);
 useEffect(()=>{if(!highlight)return;const target=root.current?.querySelector('[data-setting="'+CSS.escape(highlight)+'"]');target?.scrollIntoView({block:"center",behavior:"instant"});target?.classList.add("sm-highlight");const timer=setTimeout(()=>{target?.classList.remove("sm-highlight");setHighlight("");},1800);return()=>{clearTimeout(timer);target?.classList.remove("sm-highlight");};},[highlight,tab,expanded]);
 function set(path,value){setDraftSettings(current=>setPath(current,path,value));setErrors(current=>({...current,[path]:""}));setSaveError("");}
 function navigate(category,path=""){setTab(category);setQuery("");if(path.startsWith("loyalty.")&&path!=="loyalty.enabled")setExpanded(path.split(".")[1]);setHighlight(path);}
 function showErrors(issues){const next=Object.fromEntries(issues.map(i=>[i.path.join("."),i.message]));setErrors(next);const path=issues[0]?.path.join(".")||"businessName",match=index.find(row=>row[1]===path)||index.find(row=>path.startsWith(row[1]+"."));
   navigate(match?.[0]||"general",path);setSaveError("Check the highlighted fields before saving.");}
 async function save(){if(!dirty||lock.current)return;const parsed=settingSchema.safeParse(payload(draftSettings));if(!draftSettings.businessName.trim()){showErrors([{path:["businessName"],message:"Business Name is required."}]);return;}if(!parsed.success){showErrors(parsed.error.issues);return;}
 if(draftSettings.startingNumber<=(draftSettings.lastIssuedSequence||0)){showErrors([{path:["startingNumber"],message:"Sequence must be greater than the highest issued invoice."}]);return;}
 lock.current=true;setSaving(true);setSaveError("");try{const result=await api("/settings",{method:"PATCH",body:parsed.data});const saved=prepare(result,parsed.data.loyalty);setSavedSettings(saved);setDraftSettings(saved);setErrors({});toast.success("Settings saved successfully");}catch(error){setSaveError("Unable to save settings. "+error.message);toast.error("Unable to save settings. Please try again.");}finally{lock.current=false;setSaving(false);}}
 function discard(){setDraftSettings(savedSettings);setErrors({});setSaveError("");setConfirm(null);}
 async function confirmAction(){if(confirm.type==="reset"){try{const defaults=await api("/settings?defaults=true");setDraftSettings(prepare({...defaults,lastIssuedSequence:draftSettings.lastIssuedSequence},defaults.loyalty));setErrors({});setConfirm(null);toast.info("Defaults loaded. Review and Save Changes to apply.");}catch(e){toast.error(e.message);}return;}if(confirm.type==="leave"){skipGuard.current=true;window.location.assign(confirm.href);return;}discard();}
 const preview=formatInvoiceNumber({prefix:draftSettings.invoicePrefix,format:draftSettings.invoiceNumberFormat,sequence:Math.max(Number(draftSettings.startingNumber)||1,(draftSettings.lastIssuedSequence||0)+1),sequencePadding:Number(draftSettings.invoiceSequencePadding)||1,date:now});
 const q=query.toLowerCase().trim(),results=q?index.filter(([category,path,label])=>(label+" "+categories.find(c=>c[0]===category)[1]).toLowerCase().includes(q)):[],shown=q?categories.filter(c=>results.some(r=>r[0]===c[0])):categories;
 function previewReceipt(testPrint=false){setReceipt({testPrint,sale:{invoiceNumber:"SAMPLE · "+preview,createdAt:now.toISOString(),status:"COMPLETED",business:{name:draftSettings.businessName,address:draftSettings.address,phone:draftSettings.phone,logo:draftSettings.logo,footer:draftSettings.receiptFooter,receiptSize:draftSettings.receiptSize,receipt:draftSettings.receipt},customer:{name:"Sample Customer",phone:"9000000000"},cashier:{name:"Sample Cashier"},items:[{productName:"Fresh Juice (sample)",quantity:2,unitPrice:100,addons:[],note:""}],subtotal:200,discount:{amount:0},tax:{enabled:false},total:200,paymentMethod:"Cash",payments:[{method:"Cash",amount:200}],cashReceived:200,changeGiven:0,loyaltySummary:{cashbackEarned:10,stampEarned:1,walletRedeemed:0,rewardsUnlocked:[]}}});}
 return <SettingsContext.Provider value={{draft:draftSettings,set,errors}}><div className="settings-modern" ref={root}><header className="sm-header"><div><h1>Settings</h1><p>Manage your business, billing, checkout, payments and customer rewards.</p></div><div className="sm-actions">{dirty&&<span className="sm-dirty">● Unsaved changes</span>}<button className="button secondary" disabled={!dirty||saving} onClick={()=>setConfirm({type:"discard"})}>Discard Changes</button><button className="button primary" disabled={!dirty||saving} onClick={save}><Save size={16}/>{saving?"Saving...":"Save Changes"}</button></div></header>
 <div className="sm-search-wrap"><label className="sm-search"><Search size={18}/><input aria-label="Search settings" placeholder="Search settings, fields or features..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery("")}><X size={16}/></button>}</label>{q&&<div className="sm-results">{results.length?results.map(([category,path,label])=><button key={category+path} onClick={()=>navigate(category,path)}><strong>{label}</strong><small>{categories.find(c=>c[0]===category)[1]} →</small></button>):<p>No matching settings. Try invoice, cashback or payments.</p>}</div>}</div>
 <section className="sm-overview">{[[Building2,"Business",draftSettings.businessName.trim()?"Configured":"Needs setup","general"],[ReceiptText,"Invoice",preview,"invoice"],[CreditCard,"Payments",draftSettings.paymentMethods.length+" methods enabled","payments"],[Gift,"Loyalty",draftSettings.loyalty.enabled?[draftSettings.loyalty.wallet,draftSettings.loyalty.stamp,draftSettings.loyalty.visit,draftSettings.loyalty.birthday].filter(p=>p.enabled).length+" programs enabled":"Disabled","loyalty"]].map(([Icon,label,value,category])=><button key={category} onClick={()=>navigate(category)}><Icon size={20}/><span><small>{label}</small><strong>{value}</strong></span></button>)}</section>
 {saveError&&<div className="sm-save-error" role="alert">{saveError}</div>}
 <div className="sm-layout"><nav aria-label="Settings categories">{shown.map(([key,label,Icon])=><button key={key} className={tab===key?"active":""} aria-current={tab===key?"page":undefined} onClick={()=>navigate(key)}><Icon size={18}/>{label}</button>)}</nav><fieldset className="sm-content" disabled={saving}>{tab==="general"&&<BusinessSettings/>}{tab==="invoice"&&<InvoiceSettings preview={preview} now={now} onPreview={()=>previewReceipt()}/>} {tab==="checkout"&&<CheckoutSettings/>}{tab==="payments"&&<PaymentSettings/>}{tab==="discounts"&&<DiscountSettings/>}{tab==="loyalty"&&<LoyaltySettings expanded={expanded} setExpanded={setExpanded}/>} {tab==="printing"&&<PrintingSettings onPreview={()=>previewReceipt(true)}/>} {tab==="data"&&<DataSettings onReset={()=>setConfirm({type:"reset"})}/>}</fieldset></div>
 {confirm&&<Modal title={confirm.type==="reset"?"Reset settings to defaults?":"Discard changes?"} onClose={()=>setConfirm(null)}><div className="modal-body"><p>{confirm.type==="reset"?"Default preferences will replace your draft. Review them and use Save Changes to apply. Invoice history and customer balances are retained.":"Your unsaved settings will be lost."}</p></div><footer className="modal-footer"><button className="button secondary" onClick={()=>setConfirm(null)}>Keep Editing</button><button className="button danger" onClick={confirmAction}>{confirm.type==="reset"?"Load Defaults":"Discard"}</button></footer></Modal>}
 {receipt&&<ReceiptModal sale={receipt.sale} autoPrint={receipt.testPrint} onClose={()=>setReceipt(null)}/>}
 </div></SettingsContext.Provider>;
}
